### PR TITLE
FIX get_n_split

### PR DESCRIPTION
**Pull request by MSchmidt99**
Fixes math for get_n_split

### CODE REVIEW

**Comment by MSchmidt99** [comment]
@glemaitre these changes will fix the tests and docstring validations for [#23780](https://github.com/scikit-learn/scikit-learn/pull/23780).

**Comment by glemaitre** [comment]
The error was legit. I lower the number of `max_train_size`. I think that something that we are expecting is to have training split with the same number of samples which is the current behaviour.

**Comment by MSchmidt99** [comment]
> ### **[glemaitre](/glemaitre) ** commented [Nov 10, 2022](#issuecomment-1310040050)

If this is the case then we should rename `max_train_size` to `train_size` since the variable does not have a bounding effect and instead sets the exact train size for `'walk_forward'`.

**Comment by glemaitre** [comment]
I assume that if it was called `max_train_size`, it should have an effect in the original setting.

**Comment by MSchmidt99** [comment]
Oh I see, then just a note in the parameter description will do.

**Comment by MSchmidt99** [comment]
Will close this since it has been resolved through your PR.

**Pull request closed without merging**
